### ISSUE TITLE
connection_search_columns throws an error

### ISSUE THREAD

**Issue by bariscamli** [looker-open-source/sdk-codegen#1385]
Hi,

I added a snowflake connection to my looker instance; however, when I call it like the code below it throws an error.

```
const columns = await looker._connection.ok(looker._connection.connection_search_columns({ connection_name: "sf" }))
context.log(columns)
```

Also when I type name of bq connections, it gives me an empty array but I already see tables and columns of this connection on UI

<img width="1321" alt="image" src="https://github.com/looker-open-source/sdk-codegen/assets/49035837/20196384-6da6-4f3c-80ee-2826fc7326b1">

```
LookerSDKError: An error has occurred.
at new LookerSDKError (node_modules/@looker/sdk-rtl/lib/lookerSDKError.js:26:24)
    at sdkError (node_modules/@looker/sdk-rtl/lib/transport.js:194:14)
     at node_modules/@looker/sdk-rtl/lib/transport.js:220:13
     at Generator.next (<anonymous>)
     at asyncGeneratorStep (node_modules/@looker/sdk-rtl/lib/transport.js:21:103)
     at _next (node_modules/@looker/sdk-rtl/lib/transport.js:22:194)
     at process.processTicksAndRejections (node:internal/process/task_queues:95:5) {
   errors: [],
   documentation_url: 'https://cloud.google.com/looker/docs/r/err/4.0/500/get/connections/:connection_name/search_columns'
 }
```

**Comment by deanlooker** [comment]
Hello! 

Based on your post, it seems like you're expecting this endpoint to return data and/or metadata from the table from the `/admin/connections` page. Just to clarify - the `connection_search_columns` [endpoint](https://cloud.google.com/looker/docs/reference/looker-api/latest/methods/Metadata/connection_search_columns) is used to search the connection specified by `connection_name` for columns in the db which are exact matches of the string provided in `column_name`. As such, a `column_name` is **required** in order to successfully use this endpoint.

Here's a TypeScript example:

```
let response = await sdk.ok(connection_search_columns(sdk,
  {
    connection_name: 'thelook',
    column_name: 'order_id'
  }))
  ```
  
  Which, in my demo db, returns a response with this structure:
  
  ```
  [
    {
      "schema_name": "",
       "table_name": "order_items",
       "column_name": "order_id",
       "data_type": "int"
    },
    {
       "schema_name": "",
       "table_name": "orders",
       "column_name": "order_id",
       "data_type": "int"
    }
]
```

I think there is some room for improvement in our documentation and error handling here and will be opening a ticket internally to see if we can address that.
