### ISSUE TITLE
Better documentation and more example

### ISSUE THREAD

**Issue by funes79** [looker-open-source/sdk-codegen#151]
Hi, would it be possible to better document how to use this new python client? Was using the old `lookerapi`, and I would like to know how to read dashboards, models, read view definitions. Thanks

**Comment by joeldodge79** [comment]
hi @funes79 - thanks for engaging! we have plans for better online documentation but for now you can start with the [readme on pypi](https://pypi.org/project/looker-sdk/), and there are many more examples in our [sdk-examples](https://github.com/looker-open-source/sdk-examples/tree/master/python) repo

**Comment by jkaster** [comment]
Thanks for the request, @funes79. We'll commit PR #152 to master shortly which makes all the generated SDK files available for browsing in this repository.

I'll close this issue with PR #152 because "better documentation" is an open-ended request (that we agree with!). We will constantly be working on improving the SDK documentation, and providing better ways to explore, discover, and experiment with our APIs. If you have any additional specific requests, please feel free to create a new issue.

Thanks for trying out our new SDKs!
