### ISSUE TITLE
Is there a release schedule for the Python SDK?

### ISSUE THREAD

**Issue by mcranston18** [looker-open-source/sdk-codegen#234]
I understand the Python SDK is in pre-release and comes with the following disclaimer:

> DISCLAIMER: This is a beta version of the Looker SDK, using a completely new code generator developed by Looker. Implementations are still subject to change, but we expect most SDK method calls to work correctly. If you run into problems with the SDK, please feel free to report an issue, and please indicate which language SDK you're using in the report.

1. Is there a timeline for a stable release?
2. I am about to integrate Looker into a production application. Would you recommend using the Python SDK or making requests directly to the Looker API?

**Comment by jkaster** [comment]
We don't have an exact timeline for the Python SDK getting to stable status, but the majority of scoped functionality for 1.0 is implemented now.

We think you'll be more productive with the beta Python SDK rather than making the requests directly into Looker. We still have a few changes coming soon to the SDKs via the code generator (such as enums) but the amount of change from one version to the next is definitely getting smaller. 

There are a fair number of users having success with the beta, and we are ready to resolve any issues uncovered with it.

**Comment by mcranston18** [comment]
@jkaster Thanks very much. I will use the SDK then!
