### ISSUE TITLE
Typescript SDK: Improvement to Model Typings

### ISSUE THREAD

**Issue by JamesYeoman** [looker-open-source/sdk-codegen#452]
In a lot of places, IDictionary is used instead of a distinct type that defines what should be expected. For example, while trying to determine what properties I need from the `field` property of `IDashboardFilter`, I discovered that 3 of the properties on `IDashboardFilter` are of type `IDictionary`.

This isn't very useful information. It's basically saying "this object could have a property with a key of 'qwertyuiop'", and we all know that's never going to be a real property.

**Comment by joeldodge79** [comment]
The types generated for the SDK come from the swagger/OAS spec for the Looker API. The fact that `IDictionary.field` is not more strongly typed is because the Looker API itself doesn't offer it for that field. For now you're stuck with querying data to see what properties are actually present.

As for requesting Looker API improvements (as this would be), your best bet is to browse help.looker.com to contact support
